//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WorkFlowManagement
{
    using System;
    using System.Collections.Generic;
    
    public partial class Form
    {
        public Form()
        {
            this.Applications = new HashSet<Application>();
            this.Form_Approver = new HashSet<Form_Approver>();
        }
    
        public int ID { get; set; }
        public string Name { get; set; }
    
        public virtual ICollection<Application> Applications { get; set; }
        public virtual ICollection<Form_Approver> Form_Approver { get; set; }
    }
}
