//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WorkFlowManagement
{
    using System;
    using System.Collections.Generic;
    
    public partial class Request
    {
        public int ID { get; set; }
        public int RequestBy { get; set; }
        public string RName { get; set; }
        public string RCNIC { get; set; }
        public string RRoll_No { get; set; }
        public string RSemester { get; set; }
        public string REmail { get; set; }
        public string RAddress { get; set; }
    }
}
