//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WorkFlowManagement
{
    using System;
    using System.Collections.Generic;
    
    public partial class User
    {
        public User()
        {
            this.Applications = new HashSet<Application>();
            this.Form_Approver = new HashSet<Form_Approver>();
            this.WorkFlows = new HashSet<WorkFlow>();
        }
    
        public int User_ID { get; set; }
        public string Login { get; set; }
        public string Password { get; set; }
        public string Name { get; set; }
        public string Designation { get; set; }
        public string Email { get; set; }
        public string User_Type { get; set; }
        public Nullable<bool> IsActive { get; set; }
    
        public virtual ICollection<Application> Applications { get; set; }
        public virtual ICollection<Form_Approver> Form_Approver { get; set; }
        public virtual ICollection<WorkFlow> WorkFlows { get; set; }
    }
}
